### ISSUE TITLE
.bat crashes after saving bot.py file in PyCharm

### ISSUE THREAD

**Issue by oneunreadmail** [RLBot/RLBot#198]
This is what I get every like 5th save if I'm doing it on the go:
`INFO: bot1[      bot_manager.py:154 -                  run() ] Reloading Agent: D:\code\medivh\medivh\medivh.py
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\rlbot\setup_manager.py", line 158, in run_agent
    bm.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\rlbot\botmanager\bot_manager.py", line 150, in run
    new_module_modification_time = os.stat(agent_class_file).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\code\\medivh\\medivh\\medivh.py'`

I assume it's because PyCharm makes the file unavailable for reading for a moment, and framework doesn't recheck availability after that.

**Comment by tarehart** [comment]
Good point, that's an annoying problem! Will be fixed soon with https://github.com/RLBot/RLBot/pull/199
