### ISSUE TITLE
GUI Crashes when trying to add new loadout preset

### ISSUE THREAD

**Issue by alex-polosky** [RLBot/RLBot#257]
I'm experiencing a crash when trying to add a new loadout preset via the gui. I could modify the config by hand (which I will most likely end up doing) and also debug it myself (which, also, I will probably end up doing) but I wanted to post an issue here to see if anyone else has had this error or if they have if they've fixed it.

Steps to reproduce:
1. Launch the gui by running `python ./runner_gui.py`
1. Select a bot in the blue or orange team list
1. Click the '...' button next to Loadout Preset
1. Click the 'New' button
1. Observe this crash report:

```Python
Traceback (most recent call last):
  File "T:\code\git\RLBot\src\main\python\rlbot\gui\presets.py", line 95, in __init__
    self.agent_class = import_agent(python_file_path).get_loaded_class()
  File "T:\code\git\RLBot\src\main\python\rlbot\utils\class_importer.py", line 40, in import_agent
    return import_class_with_base(python_file, BaseAgent)
  File "T:\code\git\RLBot\src\main\python\rlbot\utils\class_importer.py", line 52, in import_class_with_base
    return ExternalClassWrapper(python_file, base_class)
  File "T:\code\git\RLBot\src\main\python\rlbot\utils\class_importer.py", line 21, in __init__
    self.loaded_class, self.loaded_module = load_external_class(self.python_file, self.base_class)
  File "T:\code\git\RLBot\src\main\python\rlbot\utils\class_importer.py", line 62, in load_external_class
    loaded_module = importlib.import_module(module_name)
  File "C:\Program Files\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'base_agent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "T:\code\git\RLBot\src\main\python\rlbot\gui\preset_editors.py", line 89, in add_new_preset
    preset = self.preset_class(self.validate_name("new preset", None))
  File "T:\code\git\RLBot\src\main\python\rlbot\gui\presets.py", line 96, in __init__
    except (ValueError, ModuleNotFoundError):
NameError: name 'ModuleNotFoundError' is not defined
```

**Comment by alex-polosky** [comment]
Figured it out: I'm using Python 3.5, which does not have ModuleNotFoundError defined. Whoops. Simply renamed any instance of that to ImportError and everything is running A OK.

**Comment by tarehart** [comment]
Thanks for following up! You might want to go ahead and get on 3.6. That's a documented requirement, and you may have more trouble in the future with 3.5.

**Comment by alex-polosky** [comment]
I generally use 3.5 for things on my main PC since I'm actively working on a project that requires it.

That being said, I'm no stranger to virtual environments so I can do that. I must have missed that somewhere. Last time I tried using RLBot was several months ago, I guess a lot must have changed! (Actually a lot has, I'm trying to migrate a bot over from the old style and am having difficulties with figuring out where boost pads are but I'll figure it out lol)
