### ISSUE TITLE
Stack trace from quick chat

### ISSUE THREAD

**Issue by tarehart** [RLBot/RLBot#427]
Bad code from me, will fix soon
```
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "C:\Users\giant\AppData\Local\RLBotGUI\Python\lib\site-packages\rlbot\setup_manager.py", line 386, in run_agent
    bm.run()
  File "C:\Users\giant\AppData\Local\RLBotGUI\Python\lib\site-packages\rlbot\botmanager\bot_manager.py", line 204, in run
    team=self.match_config.player_configs[message.PlayerIndex()].team,
IndexError: list index out of range

```

**Comment by tarehart** [comment]
Fixed in version 1.17.1
