### ISSUE TITLE
RLBot with Cracked RocketLeague ?

### ISSUE THREAD

**Issue by hesoyamhh** [RLBot/RLBot#522]
RLBot is designed to run RocketLeague via Steam. Is there a way to make it run the actual RocketLeague.exe so that people having cracked version can make use of this software too ?

I have tried to make a shortcut of RocketLeague.exe with Target:

```
"D:\Games\Rocket League\Binaries\Win64\RocketLeague.exe" {'RLBot_ControllerURL=127.0.0.1:[0-9]+','-rlbot'}
"D:\Games\Rocket League\Binaries\Win64\RocketLeague.exe" -RLBot_ControllerURL=127.0.0.1:[0-9]+ -rlbot
"D:\Games\Rocket League\Binaries\Win64\RocketLeague.exe" RLBot_ControllerURL=127.0.0.1:[0-9]+ -rlbot
```

But every time I try to start a match, it gives error:

```
RLBot.exe trying to connect to Rocket League on port 23233...
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\RLBotGUIX\venv\lib\site-packages\rlbot\setup_manager.py", line 138, in is_rocket_league_running
    ROCKET_LEAGUE_PROCESS_INFO.REQUIRED_ARGS)
  File "C:\Users\*****\AppData\Local\RLBotGUIX\venv\lib\site-packages\rlbot\utils\process_configuration.py", line 117, in is_process_running
    raise WrongProcessArgs(f"{program} is not running with required arguments: {required_args}!")
rlbot.utils.process_configuration.WrongProcessArgs: RocketLeague.exe is not running with required arguments: {'RLBot_ControllerURL=127.0.0.1:[0-9]+', '-rlbot'}!
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Users\*****\AppData\Local\RLBotGUIX\venv\lib\site-packages\rlbot_gui\match_runner\match_runner.py", line 172, in start_match_helper
    sm.connect_to_game()
  File "C:\Users\*****\AppData\Local\RLBotGUIX\venv\lib\site-packages\rlbot\setup_manager.py", line 170, in connect_to_game
    elif not self.is_rocket_league_running(port):
  File "C:\Users\*****\AppData\Local\RLBotGUIX\venv\lib\site-packages\rlbot\setup_manager.py", line 147, in is_rocket_league_running
    raise Exception(f"Rocket League is not running with {ROCKET_LEAGUE_PROCESS_INFO.REQUIRED_ARGS}!\n"
Exception: Rocket League is not running with {'RLBot_ControllerURL=127.0.0.1:[0-9]+', '-rlbot'}!
Please close Rocket League and let us start it for you instead!
2020-08-08T13:39:09Z <Greenlet at 0x20860316e18: start_match_helper([{'name': 'Human', 'team': 0, 'type': 'human', 'sk, {'map': 'DFHStadium', 'game_mode': 'Soccer', 'skip)> failed with Exception
```

Full Logs: https://pastebin.com/KchJunB9

Is there a way to make it run RocketLeague.exe directly ?

**Comment by TheBlocks** [comment]
We neither endorse nor support unofficial/cracked versions of Rocket League. Please wait until Rocket League becomes free to play to try RLBot if you do not wish to pay for Rocket League. If you have any issues then we'll be happy to help out, but we can't support cracked Rocket League users.

**Comment by hesoyamhh** [comment]
@TheBlocks Thanks for the info. I was under impression that as this was open source, you might support all kind of RocketLeague installations. Will definitely wait for the day RL is released on Epic Store :)
