### ISSUE TITLE
Starting Issue

### ISSUE THREAD

**Issue by Rolle127** [RLBot/RLBot#572]
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Users\vikto\AppData\Local\RLBotGUIX\Python37\lib\site-packages\rlbot_gui\match_runner\match_runner.py", line 223, in start_match_helper
    setup_match(sm , match_config, launcher_prefs)
  File "C:\Users\vikto\AppData\Local\RLBotGUIX\Python37\lib\site-packages\rlbot_gui\match_runner\match_runner.py", line 181, in setup_match
    do_setup()
  File "C:\Users\vikto\AppData\Local\RLBotGUIX\Python37\lib\site-packages\rlbot_gui\match_runner\match_runner.py", line 152, in do_setup
    setup_manager.connect_to_game(launcher_preference=launcher_pref)
  File "C:\Users\vikto\AppData\Local\RLBotGUIX\Python37\lib\site-packages\rlbot\setup_manager.py", line 192, in connect_to_game
    port = self.ensure_rlbot_gateway_started()
  File "C:\Users\vikto\AppData\Local\RLBotGUIX\Python37\lib\site-packages\rlbot\setup_manager.py", line 406, in ensure_rlbot_gateway_started
    self.rlbot_gateway_process, port = gateway_util.launch(launch_options)
  File "C:\Users\vikto\AppData\Local\RLBotGUIX\Python37\lib\site-packages\rlbot\gateway_util.py", line 52, in launch
    raise FileNotFoundError(f'Unable to find RLBot binary at {path}! Is your antivirus messing you up? Check '
FileNotFoundError: Unable to find RLBot binary at C:\Users\vikto\AppData\Local\RLBotGUIX\Python37\lib\site-packages\rlbot\dll\RLBot.exe! Is your antivirus messing you up? Check https://github.com/RLBot/RLBot/wiki/Antivirus-Notes.
2022-01-01T21:12:07Z <Greenlet at 0x184f0a10948: start_match_helper([{'name': 'BroccoliBot', 'team': 0, 'type': 'rlbot, {'map': 'DFHStadium', 'game_mode': 'Soccer', 'skip, RocketLeagueLauncherPreference(preferred_launcher=)> failed with FileNotFoundError

**Comment by VirxEC** [comment]
If you're still having issues, please visit the #issues-and-bugs channel in our [Discord server](https://discord.com/invite/nhdwbSz) for help.
