### ISSUE TITLE
Python error "Expected end or semicolon (after version specifier) torch>=1.5.1+cpu"

### ISSUE THREAD

**Issue by TimDev9492** [RLBot/RLBot#612]
I installed RLBot on Arch Linux using the instructions listed [here](https://github.com/RLBot/RLBot/wiki/Operating-System-Support#instructions). Whenever I run the script with the commands as per instruction, the GUI opens just fine. But when I try to add the RLBotPack, I get the following error in the terminal:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 126, in _parse_requirement_details
    marker = _parse_requirement_marker(
  File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 147, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "/usr/lib/python3.10/site-packages/packaging/_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
    torch>=1.5.1+cpu
         ~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/.local/lib/python3.10/site-packages/eel/__init__.py", line 318, in _process_message
    return_val = _exposed_functions[message['name']](*message['args'])
  File "/home/tim/.local/lib/python3.10/site-packages/rlbot_gui/gui.py", line 331, in scan_for_bots
    bots = get_bots_from_directory(folder)
  File "/home/tim/.local/lib/python3.10/site-packages/rlbot_gui/gui.py", line 376, in get_bots_from_directory
    return [serialize_bundle(bundle) for bundle in bundles]
  File "/home/tim/.local/lib/python3.10/site-packages/rlbot_gui/gui.py", line 376, in <listcomp>
    return [serialize_bundle(bundle) for bundle in bundles]
  File "/home/tim/.local/lib/python3.10/site-packages/rlbot_gui/gui.py", line 112, in serialize_bundle
    'missing_python_packages': [r.line for r in bundle.get_missing_python_packages() + bundle.get_python_packages_needing_upgrade()],
  File "/home/tim/.local/lib/python3.10/site-packages/rlbot/parsing/bot_config_bundle.py", line 66, in get_missing_python_packages
    return get_missing_packages(requirements_file=self.requirements_file, special_reqs=special_reqs)
  File "/home/tim/.local/lib/python3.10/site-packages/rlbot/utils/requirements_management.py", line 39, in get_missing_packages
    needed += [r for r in requirements.parse(fd) if r.specifier]
  File "/home/tim/.local/lib/python3.10/site-packages/rlbot/utils/requirements_management.py", line 39, in <listcomp>
    needed += [r for r in requirements.parse(fd) if r.specifier]
  File "/home/tim/.local/lib/python3.10/site-packages/requirements/parser.py", line 87, in parse
    yield Requirement.parse(line)
  File "/home/tim/.local/lib/python3.10/site-packages/requirements/requirement.py", line 254, in parse
    return cls.parse_line(line)
  File "/home/tim/.local/lib/python3.10/site-packages/requirements/requirement.py", line 232, in parse_line
    pkg_req = Req.parse(line)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3211, in parse
    (req,) = parse_requirements(s)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3170, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
    torch>=1.5.1+cpu
         ~~~~~~~^

```

I'm using Python version `3.10.10`

**Comment by JakeDevs** [comment]
Same here, on arch as well. Seems a few other people in the discord had the same issue from over 2 years ago.

**Comment by JakeDevs** [comment]
Just wanted to say that it's working with wine so if you're on epic you can just do that. However if you're on steam this wont work so you have to use protontricks. You then have to manually install pip because it's broken by default and then try.

**Comment by JakeDevs** [comment]
better solution use this instead https://github.com/VirxEC/rlbot_gui_rust

**Comment by VirxEC** [comment]
Fixed
